script:
- |-
  git config user.name "manaswinidas"
  git config user.email "dasmanaswini10@gmail.com"
  git remote remove origin
  git remote add origin https://$GITHUB_API_KEY@github.com/manaswinidas/kogito-docs.git > /dev/null 2>&1
  git remote add upstream https://$GITHUB_API_KEY@github.com/manaswinidas/kogito-docs.wiki.git > /dev/null 2>&1
  git fetch origin
  git fetch upstream
  git merge upstream/master --no-edit
  git push origin HEAD:master > /dev/null 2>&1
  git push upstream HEAD:master > /dev/null 2>&1
env:
  matrix:
    secure: oEKy0Kp7d0AqwcVcC/+4bZalZbqffEM8CpReqkZEgcNt2V570fEnWQRGwvyVKO59jaysa/SUf+LAyzl1i5p9ShA7DgTgRx08org0diazzpwxB1GK5Am3OdlYtgp4iU736QFKTTPi68WteCC/DW7L3sB3PCsfp5Mmp16gkqdUieBFsCWT1hg0hT0i2ki7ihwjPKOnSoAlB4hMwJuyq26FV1i9/yrheeCeccAHeHjKzT4Nob6xRv3WMo2HbVfPF1LELTydny6/X0IOA44mK3YmVL6v7AhEPRRSr3n0twcHTdhK+qEMmMc7rddWCYe53EASO/RMT1fAK6Bj2MzFApnzKbBGIEwGrbH+mMtAZdBj/gemBU+ge+rAfK6pBLegrC0c1o9xXEWmXbMGlv46jdGH0QL3teFx+Ov0/OsTFftmpizLDZrgWqez6JJmz2a1gnQpl+f7PNxjJfmnD3pgXnb5vQ3O50A7gybyViZvaxz0cgq0p23FddZAoRgkq/0Xq0XLdjK2Tbe01euSRrNUFeFhNBebgOkuzGNB0oNyazq7E6PLpbCdAVDXzLADUjmo0iHtM8DBIHB5vAs9gtqDpLpBYeiLmWYbs6tVpSFDnTSCyeQF6lTfFsbd0u0nHWUChtGIWGqdc5QkwqgoC6O5nZE8owQVi3tUl5RyxMVYyxx1BZc=
