Our roadmap tries to give a high-level overview of our plans for upcoming Kogito releases in the community.  More details are tracked in https://issues.redhat.com/projects/KOGITO/summary[our JIRA project].

= Upcoming releases

The goal is to have a new minor community release every month.

# 0.7.0

## Release date - mid-January 2020

### Main themes of the release 

* operator to provision jobs service

# 0.8.0

## Release date - mid-February 2020

### Main themes of the release 

* process management console for process administrators
* operator to provision SSO, management console


# 1.0.0

## Release date - first half of 2020

### Main themes of the release 

* Full end-to-end workflow
* Documentation for all components
* Getting started experience


= Older releases

# 0.6.0

## Release date - December 2019

### Main themes of the release 

* filtering by domain data in data index service
* jobs service to externalise timers
* integration with keycloak for security
* spring boot starter
* moved to RESTEasy for spring boot runtimes instead of Apache CXF

Detailed release notes can be found https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12322421&version=12342524[here]

# 0.5.0

## Release date - mid-October 2019

### Main themes of the release 

* DMN generated REST endpoints that provide access to evaluating entire model or defined decision services
* Support for intermediate and boundary events for messages and timers - timers are currently in memory only 
* Support for cloud events payload when using message events which enables correlation between processes that exchange messages
* Support for embedded subprocess
* GraphQL subscription for both domain and technical data types (e.g. process instances, user tasks)
* Quarkus extension has moved from JSON be to JACKSON for JSON marshalling … so in case you use kogito-maven-plugin directly you most likely need to update dependencies - see kogito-examples
* Initial version for security enabled REST endpoints for processes - it currently relies on manual XML editing as there is no support in tooling for it
* published version of VSCode editors for BPMN and DMN
* BPMN/DMN chrome extension alpha

Detailed release notes can be found https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12322421&version=12342522[here]

# 0.4.0

## Release date - mid-September 2019

### Main themes of the release 

* configurable human tasks life cycle to allow control over what is needed to work on user-assigned tasks
* operator provision data index and runtime storage on demand
* integrate Rules with jBPM codegen
* expose KieBase and KieSession configuration options also in Rule Units
* first automatically generated REST endpoint for DMN 
* BPMN VSCode editor alpha version

Detailed release notes can be found https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12322421&version=12342521[here]


# 0.3.0

## Release date - mid-August 2019

### Main themes of the release 

* runtime persistence based on Infinispan
* data index service initial implementation to enable management and human task-centric use cases
* events for runtime based on CloudEvents - this is integration between runtime services and data index service
* enable domain-specific metrics - mainly data-driven to be available for dashboards
* new version of the operator with a new redesign and smooth integration with a service discovery engine
* introduce the kogito cli for operator
* initial Data Source and Data Stream implementation
* Rule Unit support with concurrent Rule Unit prototype
* Rule Unit automated endpoint generation with query response
* automated POJO REST endpoint generation

Detailed release notes can be found https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12322421&version=12342520[here]


# 0.2.0

## Release date - mid-July 2019

### Main themes of the release 

* message start and end events that allow smooth integration with Apache Kafka and possibly other messaging
* multi-instance characteristic for service nodes and reusable subprocesses
* Unit of Work support to allow finer control of execution and grouping related operations
* refactor service discovery when running in Kubernetes based environments

Detailed release notes can be found https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12322421&version=12342354[here]